# Generated by Django 2.0.4 on 2018-04-21 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comeback',
            fields=[
                ('comeback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comeback_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('fight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Insult',
            fields=[
                ('insult_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insult_text', models.CharField(max_length=1000)),
                ('correct_comeback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fight.Comeback')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('script_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('insult_comeback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fight.Insult')),
            ],
        ),
    ]
