# Generated by Django 2.0.4 on 2018-04-21 14:48

from django.db import migrations

from fight.models import Comeback, Insult


def import_insults_and_comebacks(apps, schema_editor):
    comeback = Comeback(comeback_text='I\'m glad to hear you attended your family reunion.')
    comeback.save()

    insult = Insult(insult_text='Now I know what filth and stupidity really are.', correct_comeback=comeback)
    insult.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_insults_and_comebacks)
    ]
