# Generated by Django 2.0.4 on 2018-04-21 14:48
import math

from django.db import migrations

from fight.models import Comeback, Insult

insults_and_comebacks = ["You fight like a Dairy Farmer!",
                         "How appropriate! You fight like a cow!",
                         "This is the END for you, you gutter crawling cur!",
                         "And I've got a little TIP for you, get the POINT?",
                         "I've spoken with apes more polite than you!",
                         "I'm glad to hear you attended your family reunion!",
                         "Soon you'll be wearing my sword like a shish kebab!",
                         "First you better stop waving it about like a feather duster.",
                         "People fall at my feet when they see me coming!",
                         "Even BEFORE they smell your breath?",
                         "I'm not going to take your insolence sitting down!",
                         "Your hemorroids are flaring up again eh?",
                         "I once owned a dog that was smarter than you.",
                         "He must have taught you everything you know.",
                         "Nobody's ever drawn blood from me and nobody ever will.",
                         "You run THAT fast?",
                         "Have you stopped wearing diapers yet?",
                         "Why? Did you want to borrow one?",
                         "There are no words for how disgusting you are.",
                         "Yes there are. You just never learned them.",
                         "You make me want to puke.",
                         "You make me think somebody already did.",
                         "My handkerchief will wipe up your blood!",
                         "So you got that job as janitor, after all.",
                         "I got this scar on my face during a mighty struggle!",
                         "I hope now you've learned to stop picking your nose.",
                         "I've heard you are a contemptible sneak.",
                         "Too bad no one's ever heard of YOU at all.",
                         "You're no match for my brains, you poor fool.",
                         "I'd be in real trouble if you ever used them.",
                         "You have the manners of a beggar.",
                         "I wanted to make sure you'd feel comfortable with me."]


def import_insults_and_comebacks(apps, schema_editor):
    for i in range(0, math.floor(len(insults_and_comebacks) / 2)):
        comeback = Comeback(text=insults_and_comebacks[i*2])
        comeback.save()

        insult = Insult(text=insults_and_comebacks[i*2 + 1], correct_comeback=comeback)
        insult.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_insults_and_comebacks)
    ]
