# Generated by Django 2.0.4 on 2018-04-21 14:48
import math

from django.db import migrations

from fight.models import Comeback, Insult

insults_and_comebacks = ["Now I know what filth and stupidity really are.",
                         "I'm glad to hear you attended your family reunion.",
                         "Every word you say to me is stupid.",
                         "I wanted to make sure you'd feel comfortable with me.",
                         "I've  got a long, sharp lesson for you to learn today.",
                         "And I've got a little TIP for you. Get the POINT?",
                         "I will milk every drop of blood from your body!",
                         "How appropriate, you fight like a cow!",
                         "I've got the courage and skill of a master swordsman.",
                         "I'd be in real trouble if you ever used them.",
                         "My tongue is sharper than any sword",
                         "First, you'd better stop waving it like a feather-duster.",
                         "My name is feared in every dirty corner of this island!",
                         "So you got that job as a janitor, after all.",
                         "My wisest enemies run away at the first sight of me!",
                         "Even BEFORE they smell your breath?",
                         "Only once have I met such a coward!",
                         "He must have taught you everything you know.",
                         "If your brother's like you, better to marry a pig.",
                         "You make me think somebody already did.",
                         "No one will ever catch ME fighting as badly as you do.",
                         "You run THAT fast?",
                         "My last fight ended with my hands covered with blood.",
                         "I hope now you've learned to stop picking your nose.",
                         "I hope you have a boat ready for a quick escape.",
                         "Why, did you want to borrow one?",
                         "My sword is famous all over the Caribbean!",
                         "Too bad no one's ever heard of YOU at all.",
                         "You are a pain in the backside, sir!",
                         "Your hemorrhoids are flaring up again, eh?",
                         "I usually see people like you passed-out on tavern floor.",
                         "I'm glad to hear you attended your family reunion.",
                         "There are no clever moves that can help you now.",
                         "Yes there are. You just never learned them."]


def import_insults_and_comebacks(apps, schema_editor):
    for i in range(0, math.floor(len(insults_and_comebacks) / 2)):
        comeback = Comeback(comeback_text=insults_and_comebacks[i*2])
        comeback.save()

        insult = Insult(insult_text=insults_and_comebacks[i*2 + 1], correct_comeback=comeback)
        insult.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_insults_and_comebacks)
    ]
