# Generated by Django 2.0.4 on 2018-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0003_auto_20180421_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='step_index',
            field=models.IntegerField(default=0),
        ),
    ]
