# Generated by Django 2.0.4 on 2018-04-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0004_auto_20180421_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightStepOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fight.Step')),
            ],
        ),
    ]
